FROM python:3.11-slim

WORKDIR /app

# Копируем requirements.txt из корня проекта
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бэкенда
COPY backend/ .

# Указываем рабочую директорию (на всякий случай)
WORKDIR /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]